name: Run Konveyor nightly main branch tests

on:
  schedule:
    - cron: "5 3 * * *"
  workflow_dispatch:

jobs:
  main-nightly:
    uses: ./.github/workflows/global-ci-bundle.yml
    with:
      operator_bundle: quay.io/konveyor/tackle2-operator-bundle:latest
      api_tests_ref: main
      run_api_tests: true
      ui_tests_ref: main
      # Disabled while we wait for stability, enable when UI tests get green
      run_ui_tests: false
  report_failure:
    needs: main-nightly
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send failure data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "test": "E2E",
              "branch": "main",
              "note": "Failed run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
